spring:
  datasource:
    url: jdbc:mysql://localhost:3306/leyou?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: user-service
server:
  port: 8081
mybatis:
  type-aliases-package: cn.itcast.pojo
  # 注册 eureka 服务客户端
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka